// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aiafzwftufbtjmbhepip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpYWZ6d2Z0dWZidGptYmhlcGlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNzU4ODQsImV4cCI6MjA2MTc1MTg4NH0.kB2h9Dyau4kTowC2nWl_T9PwVgozKaRTkIbc0D4DgEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);